### ISSUE TITLE
is there a way to capture TX packets?

### ISSUE THREAD

**Issue by lulitao1997** [rigtorp/efvicap#2]
I tried to replace `ef_vi_receive_...` with `ef_vi_transmit_...` in "Refill the RX descriptor ring" segment but it did not work.

Looking forward for your help.

**Comment by rigtorp** [comment]
Yes, there is. You need to have the performance monitoring license or solare capture license on the NIC. Check the manuals for the API calls you need to enable it.

**Comment by lulitao1997** [comment]
Thanks, looks like `ef_filter_spec_set_tx_port_sniff` will do the trick

**Comment by rigtorp** [comment]
I would love it if you could create a PR adding a option for this to efvicap!

**Comment by lulitao1997** [comment]
Sure, i'll make a PR after testing on supported card--

**Comment by yevgenir** [comment]
@lulitao1997 Did you manage to capture the TX packets?

**Comment by rigtorp** [comment]
See PR #3
